#server:
#  port: 8888]
spring:
  profiles:
    active: dev
#设置字符编码
#spring:
#  http:
#    encoding:
#      charset: GBK

#debug: true

#通过配置文件为对象赋值
student:
  id: 1
  name: "张三"
  address: #{schoolAddress: "taiyuan",homeAddress: "qinXian"} 行内写法
    schoolAddress: "taiyuan"
    homeAddress: "qinXian"
  location: [a:aa,b:bb,c:cc]
#     a: aa
#     b: bb
#     c: cc
  skills:
    - java
    - c#
  skills2:
    - cc
    - dd
name2: name2

