server:
  port: 8888

spring:
  mail:
    host: smtp.163.com
    username: qx_leizige@163.com
    password: Zxc233
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    properties:
      smtp:
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
        auth: true
      starttls:
        enable: true
        required: true
