server:
  port: 8888

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

uploadDir: F:\upload\

excel:
  fileName: 模板文件.xls
  filePath: F:\DownLoad\

oss:
  endpoint: ~~~~~~~
  accessKeyId: ~~~~~~
  accessKeySecret: ~~~~~~
  bucketName: ~~~~~~

