server:
  port: 8888

## 设置数据库相关
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxcv
    ##C3p0
    type: com.mchange.v2.c3p0.ComboPooledDataSource
#配置Mybatis
mybatis:
  # 设置 mapper 接口对应 XMl 配置文件的路径
  mapper-locations: /mapper/*.xml
  # 设置 MyBatis mapper 的别名所在的包
  type-aliases-package: com.bootc3p0.entity


##打印Sql日志，配置文件中设置logging.level.包名=debug即可
logging:
  level:
    com.bootc3p0.repository: debug
